export { AuthSwagger } from "./auth.swagger";
export { UsersSwagger } from "./users.swagger";
export { CoursesSwagger } from "./courses.swagger";
export { CourseContentSwagger, VideosSwagger } from "./course-content.swagger";
export { NotificationsSwagger } from "./notifications.swagger";
export { PushNotificationsSwagger } from "./push-notifications.swagger";
export { UniversitiesSwagger } from "./universities.swagger";
export { CategoriesSwagger } from "./categories.swagger";
export { PublicCoursesSwagger } from "./public-courses.swagger";
export { CoursePurchasesSwagger } from "./course-purchases.swagger";
export { StorageSwagger } from "./storage.swagger";
export { PaymentsSwagger } from "./payments.swagger";
